[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirect alternate domains to primary domain
[[redirects]]
  from = "https://emergentservice.net/*"
  to = "https://emergentservices.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://emergentservice.com/*"
  to = "https://emergentservices.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://emergentservices.net/*"
  to = "https://emergentservices.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://emergentservices.support/*"
  to = "https://emergentservices.com/:splat"
  status = 301
  force = true
